lab 3 path done
Firestorm01X2/atom pull request #113
Opened 2019-04-09 21:29 UTC by Ryuugamine

2019-04-10 13:45 UTC, Firestorm01X2 commented
В название PR мы договаривались писать - ФИО, группу и номер лабораторной.
У вас только номер лабораторной.
А вы кто вообще?

2019-04-10 16:19 UTC, Ryuugamine commented
забыл подписать

2019-04-18 16:46 UTC, Firestorm01X2 requested changes

2019-04-18 16:46 UTC, Firestorm01X2 commented on lecture04/src/main/java/ru/atom/chat/server/ChatController.java
> +    private List<String> messages = new ArrayList<>();
Использование ConcurrentLinkedQueue в данном случае необходимо, т.к. вы обращаетесь к данной коллекции из разных потоков.

2019-10-01 16:36 UTC, Firestorm01X2 commented
Закрываю.

2019-10-01 16:36 UTC, closed without merging