Lab2 Орехова Е. А. 1-41м
Firestorm01X2/atom pull request #49
Opened 2019-03-10 12:40 UTC by EkaterinaOrekhova

Реализована игра, добавлены тесты и логгер

2019-03-11 17:47 UTC, Firestorm01X2 requested changes

2019-03-11 17:47 UTC, Firestorm01X2 commented on homeworks/HW2/src/main/java/ru/example/BullsAndCows.java
> +        String word = getWordFromFile(Random.nextInt(52976));
Исправьте пожалуйста эту дикость с 52976.

Я подставил вместо вашего dictionary.txt свой, меньшего размера, и словил:

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 22633, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at ru.example.BullsAndCows.getWordFromFile(BullsAndCows.java:111)
	at ru.example.BullsAndCows.playGame(BullsAndCows.java:55)
	at ru.example.BullsAndCows.main(BullsAndCows.java:35)
```

2019-03-12 09:53 UTC, EkaterinaOrekhova commented
В процессе исправления checkstyle

2019-03-12 16:49 UTC, Firestorm01X2 approved these changes

2019-03-12 16:49 UTC, Firestorm01X2 commented
На будущуее - смотрите, что коммитите. Файл с логами на сервере ненужны.

2019-03-12 16:50 UTC, Firestorm01X2 commented
Принято с оценкой 5.

2019-03-12 16:50 UTC, closed without merging