Лаб2 Беляев А. В. 1-47м
Firestorm01X2/atom pull request #57
Opened 2019-03-11 18:38 UTC by Ryuugamine

2019-03-12 05:09 UTC, Firestorm01X2 commented
Pull request сделан не в ту ветку. Нужно в ветку lab2, а не в master.

2019-03-13 09:35 UTC, Firestorm01X2 commented
Уберите [WIP] из названия темы, если PR готов к проверке.

2019-03-13 09:49 UTC, Ryuugamine commented
Он изначально был к ней готов

2019-03-13 10:26 UTC, Firestorm01X2 commented
>Он изначально был к ней готов

Ага, я переименовал тогда сам.

Вопрос- а почему у сборка при помощи TravisCI не стартует? Попробуйте сделать ещё один коммит (любой, правка комментария, например) и запушить его.

2019-03-13 15:55 UTC, Firestorm01X2 requested changes

2019-03-13 15:55 UTC, Firestorm01X2 commented on homeworks/HW2/BullsAdnCows/build.gradle
> +}
У вас не подлкючен плагин checkstyle. В задании было требование подключить его. Исправляйте.

Далее TravisCI нацелен  на atom\homeworks\HW2 , а не atom\homeworks\HW2\BullsAdnCows\.

Я просил держать проект в HW2, а не во вложенных папках. Понятно, почему Travis не начинает сборку и запуск тестов.

2019-03-13 19:03 UTC, Firestorm01X2 commented
Не успели.

2019-03-19 17:44 UTC, Firestorm01X2 commented
Все ещё не подключен плагин checkstyle.

2019-10-01 16:36 UTC, Firestorm01X2 commented
Закрываю.

2019-10-01 16:36 UTC, closed without merging